services:
  housing:
    build: .
    container_name: phdata-housing-dev
    volumes:
      - .:/app                    # Mount current directory for live code changes
      - model-data:/app/model     # Named volume for model persistence
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1        # Show Python output in real-time
    ports:
      - "8000:8000"
    working_dir: /app
    stdin_open: true              # Keep STDIN open for interactive commands
    tty: true                     # Allocate a pseudo-TTY
    command: sleep infinity       # Keep container running without executing script

volumes:
  model-data:
    driver: local